plugins: [jekyll-paginate, jekyll-gist, jekyll-analytics]

# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

# Permalinks
permalink:        pretty

# Setup
title:            Castle Codestein
tagline:          'On code and stuff'
description:      'On code and stuff'
baseurl:          /

author:
  name:           'Tomasz Krug'
  url:            https://edhendil.github.io

paginate:         10

# Custom vars
version:          1.0

github:
  repo:           https://github.com/castlecodestein

# Analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-54491798-1       # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
